POST http://localhost:8080/integration/login
ContentType: applicaton
data{
"name":"123",
"password":"123"
}

###
POST http://localhost:8080/integration/login
content-type: application/json

{
    "name": "123",
    "password": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST http://lidongliang.top/integration/login
content-type: application/json

{
    "name": "123",
    "password": "Wed, 21 Oct 2015 18:27:50 GMT"
}
